default: &default
  adapter: sqlserver
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: Deluxe_SQLLogin_1
  password: jtxyr8dzuo
  host: OperacionDeluxeSweatDB.mssql.somee.com
  database: OperacionDeluxeSweatDB
  port: 1433
  trust_server_certificate: true

development:
  <<: *default

test:
  <<: *default

production:
  primary:
    <<: *default
  cache:
    <<: *default
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    migrations_paths: db/cable_migrate
